"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Cabritage.py']
DATA_FILES = ['sketch.sh']
OPTIONS = {'arch': 'x86_64',
 'dist_dir': '/Applications',
 'resources': 'requirements.txt,cabritage.yml'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
